version: 2

jobs:
  build:
    docker:
      - image: circleci/node:12.13.0-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install Yarn
          command: sudo npm install -g yarn@1.6.0

      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
          - v2-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}

      - run: yarn lint

      - run:
          name: Format
          command: |
            yarn format;
            git diff --exit-code --quiet;
            if [ $? = 1 ]; then
              echo 'Unformat file(s) found.';
              exit 1
            fi
