export default [
  { label: '1C:Enterprise (v7, v8)', language: '1c' },
  { label: 'Augmented Backus-Naur Form', language: 'abnf' },
  { label: 'Access log', language: 'accesslog' },
  { label: 'ActionScript', language: 'actionscript' },
  { label: 'Ada', language: 'ada' },
  { label: 'AngelScript', language: 'angelscript' },
  { label: 'Apache', language: 'apache' },
  { label: 'AppleScript', language: 'applescript' },
  { label: 'ArcGIS Arcade', language: 'arcade' },
  { label: 'Arduino', language: 'arduino' },
  { label: 'ARM Assembly', language: 'armasm' },
  { label: 'AsciiDoc', language: 'asciidoc' },
  { label: 'AspectJ', language: 'aspectj' },
  { label: 'AutoHotkey', language: 'autohotkey' },
  { label: 'AutoIt', language: 'autoit' },
  { label: 'AVR Assembler', language: 'avrasm' },
  { label: 'Awk', language: 'awk' },
  { label: 'Microsoft Axapta (now Dynamics 365)', language: 'axapta' },
  { label: 'Bash', language: 'bash' },
  { label: 'Basic', language: 'basic' },
  { label: 'Backus–Naur Form', language: 'bnf' },
  { label: 'Brainfuck', language: 'brainfuck' },
  { label: 'C/AL', language: 'cal' },
  { label: 'Cap’n Proto', language: 'capnproto' },
  { label: 'Ceylon', language: 'ceylon' },
  { label: 'Clean', language: 'clean' },
  { label: 'Clojure REPL', language: 'clojure-repl' },
  { label: 'Clojure', language: 'clojure' },
  { label: 'CMake', language: 'cmake' },
  { label: 'CoffeeScript', language: 'coffeescript' },
  { label: 'Coq', language: 'coq' },
  { label: 'Caché Object Script', language: 'cos' },
  { label: 'C++', language: 'cpp' },
  { label: 'crmsh', language: 'crmsh' },
  { label: 'Crystal', language: 'crystal' },
  { label: 'C#', language: 'cs' },
  { label: 'CSP', language: 'csp' },
  { label: 'CSS', language: 'css' },
  { label: 'D', language: 'd' },
  { label: 'Dart', language: 'dart' },
  { label: 'Delphi', language: 'delphi' },
  { label: 'Diff', language: 'diff' },
  { label: 'Django', language: 'django' },
  { label: 'DNS Zone file', language: 'dns' },
  { label: 'Dockerfile', language: 'dockerfile' },
  { label: 'DOS .bat', language: 'dos' },
  { label: 'dsconfig', language: 'dsconfig' },
  { label: 'Device Tree', language: 'dts' },
  { label: 'Dust', language: 'dust' },
  { label: 'Extended Backus-Naur Form', language: 'ebnf' },
  { label: 'Elixir', language: 'elixir' },
  { label: 'Elm', language: 'elm' },
  { label: 'ERB (Embedded Ruby)', language: 'erb' },
  { label: 'Erlang REPL', language: 'erlang-repl' },
  { label: 'Erlang', language: 'erlang' },
  { label: 'Excel', language: 'excel' },
  { label: 'FIX', language: 'fix' },
  { label: 'Flix', language: 'flix' },
  { label: 'Fortran', language: 'fortran' },
  { label: 'F#', language: 'fsharp' },
  { label: 'GAMS', language: 'gams' },
  { label: 'GAUSS', language: 'gauss' },
  { label: 'G-code (ISO 6983)', language: 'gcode' },
  { label: 'Gherkin', language: 'gherkin' },
  { label: 'GLSL', language: 'glsl' },
  { label: 'GML', language: 'gml' },
  { label: 'Go', language: 'go' },
  { label: 'Golo', language: 'golo' },
  { label: 'Gradle', language: 'gradle' },
  { label: 'Groovy', language: 'groovy' },
  { label: 'Haml', language: 'haml' },
  { label: 'Handlebars', language: 'handlebars' },
  { label: 'Haskell', language: 'haskell' },
  { label: 'Haxe', language: 'haxe' },
  { label: 'HSP', language: 'hsp' },
  { label: 'HTMLBars', language: 'htmlbars' },
  { label: 'HTTP', language: 'http' },
  { label: 'Hy', language: 'hy' },
  { label: 'Inform 7', language: 'inform7' },
  { label: 'TOML, also INI', language: 'ini' },
  { label: 'IRPF90', language: 'irpf90' },
  { label: 'ISBL', language: 'isbl' },
  { label: 'Java', language: 'java' },
  { label: 'JavaScript', language: 'javascript' },
  { label: 'jboss-cli', language: 'jboss-cli' },
  { label: 'JSON / JSON with Comments', language: 'json' },
  { label: 'Julia REPL', language: 'julia-repl' },
  { label: 'Julia', language: 'julia' },
  { label: 'Kotlin', language: 'kotlin' },
  { label: 'Lasso', language: 'lasso' },
  { label: 'LDIF', language: 'ldif' },
  { label: 'Leaf', language: 'leaf' },
  { label: 'Less', language: 'less' },
  { label: 'Lisp', language: 'lisp' },
  { label: 'LiveCode', language: 'livecodeserver' },
  { label: 'LiveScript', language: 'livescript' },
  { label: 'LLVM IR', language: 'llvm' },
  { label: 'LSL (Linden Scripting Language)', language: 'lsl' },
  { label: 'Lua', language: 'lua' },
  { label: 'Makefile', language: 'makefile' },
  { label: 'Markdown', language: 'markdown' },
  { label: 'Mathematica', language: 'mathematica' },
  { label: 'Matlab', language: 'matlab' },
  { label: 'Maxima', language: 'maxima' },
  { label: 'MEL', language: 'mel' },
  { label: 'Mercury', language: 'mercury' },
  { label: 'MIPS Assembly', language: 'mipsasm' },
  { label: 'Mizar', language: 'mizar' },
  { label: 'Mojolicious', language: 'mojolicious' },
  { label: 'Monkey', language: 'monkey' },
  { label: 'MoonScript', language: 'moonscript' },
  { label: 'N1QL', language: 'n1ql' },
  { label: 'Nginx', language: 'nginx' },
  { label: 'Nim (formerly Nimrod)', language: 'nimrod' },
  { label: 'Nix', language: 'nix' },
  { label: 'NSIS', language: 'nsis' },
  { label: 'Objective-C', language: 'objectivec' },
  { label: 'OCaml', language: 'ocaml' },
  { label: 'OpenSCAD', language: 'openscad' },
  { label: 'Oxygene', language: 'oxygene' },
  { label: 'Parser3', language: 'parser3' },
  { label: 'Perl', language: 'perl' },
  { label: 'pf.conf', language: 'pf' },
  { label: 'PostgreSQL SQL dialect and PL/pgSQL', language: 'pgsql' },
  { label: 'PHP', language: 'php' },
  { label: 'plaintext', language: 'plaintext' },
  { label: 'Pony', language: 'pony' },
  { label: 'PowerShell', language: 'powershell' },
  { label: 'Processing', language: 'processing' },
  { label: 'Python profile', language: 'profile' },
  { label: 'Prolog', language: 'prolog' },
  { label: 'Properties', language: 'properties' },
  { label: 'Protocol Buffers', language: 'protobuf' },
  { label: 'Puppet', language: 'puppet' },
  { label: 'PureBASIC', language: 'purebasic' },
  { label: 'Python', language: 'python' },
  { label: 'Q', language: 'q' },
  { label: 'QML', language: 'qml' },
  { label: 'R', language: 'r' },
  { label: 'ReasonML', language: 'reasonml' },
  { label: 'RenderMan RIB', language: 'rib' },
  { label: 'Roboconf', language: 'roboconf' },
  { label: 'Microtik RouterOS script', language: 'routeros' },
  { label: 'RenderMan RSL', language: 'rsl' },
  { label: 'Ruby', language: 'ruby' },
  { label: 'Oracle Rules Language', language: 'ruleslanguage' },
  { label: 'Rust', language: 'rust' },
  { label: 'SAS', language: 'sas' },
  { label: 'Scala', language: 'scala' },
  { label: 'Scheme', language: 'scheme' },
  { label: 'Scilab', language: 'scilab' },
  { label: 'SCSS', language: 'scss' },
  { label: 'Shell Session', language: 'shell' },
  { label: 'Smali', language: 'smali' },
  { label: 'Smalltalk', language: 'smalltalk' },
  { label: 'SML (Standard ML)', language: 'sml' },
  { label: 'SQF', language: 'sqf' },
  { label: 'SQL (Structured Query Language)', language: 'sql' },
  { label: 'Stan', language: 'stan' },
  { label: 'Stata', language: 'stata' },
  { label: 'STEP Part 21', language: 'step21' },
  { label: 'Stylus', language: 'stylus' },
  { label: 'SubUnit', language: 'subunit' },
  { label: 'Swift', language: 'swift' },
  { label: 'Tagger Script', language: 'taggerscript' },
  { label: 'Test Anything Protocol', language: 'tap' },
  { label: 'Tcl', language: 'tcl' },
  { label: 'TeX', language: 'tex' },
  { label: 'Thrift', language: 'thrift' },
  { label: 'TP', language: 'tp' },
  { label: 'Twig', language: 'twig' },
  { label: 'TypeScript', language: 'typescript' },
  { label: 'Vala', language: 'vala' },
  { label: 'VB.NET', language: 'vbnet' },
  { label: 'VBScript in HTML', language: 'vbscript-html' },
  { label: 'VBScript', language: 'vbscript' },
  { label: 'Verilog', language: 'verilog' },
  { label: 'VHDL', language: 'vhdl' },
  { label: 'Vim Script', language: 'vim' },
  { label: 'Intel x86 Assembly', language: 'x86asm' },
  { label: 'XL', language: 'xl' },
  { label: 'HTML/XML', language: 'xml' },
  { label: 'XQuery', language: 'xquery' },
  { label: 'YAML', language: 'yaml' },
  { label: 'Zephir', language: 'zephir' }
]
